# Generated by Django 4.2.6 on 2023-11-23 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
